### ISSUE TITLE
有没有类似布丁扫描的AI文档修复的python代码

### ISSUE THREAD

**Issue by nissansz** [tumuyan/SourceBook-Dataset#10]
有没有类似布丁扫描的AI文档修复的python代码

**Comment by tumuyan** [comment]
以我有限的经验，还没有看到那种项目。
从想当然的角度讲，做漂白、去阴影、去摩尔纹甚至可能并不需要ai。

**Comment by nissansz** [comment]
有没有好的前处理代码？漂白、去阴影、去摩尔纹，矫正倾斜等

**Comment by tumuyan** [comment]
代码我不熟，现成的软件不少。比如老马的 ComicEnhancerPro以及一些付费软件。

**Comment by nissansz** [comment]
好的，谢谢

**Comment by nissansz** [comment]
好的，谢谢

**Comment by Charltsing** [comment]
https://www.cnblogs.com/Charltsing/p/PictureMagick.html 这个软件提供了你需要的AI接口，唯一的问题的它是收费的
