### ISSUE TITLE
invalid gpu device

### ISSUE THREAD

**Issue by flash201524** [tumuyan/SourceBook-Dataset#11]
vkEnumeratePhysicalDevices failed 5
[Model]models/RealESRGAN-SourceBook-latest-fp16.bin
invalid gpu device

**Comment by flash201524** [comment]
GPU是RTX 3060 laptop

**Comment by tumuyan** [comment]
软件依赖Vulkan API，这个提示是软件通过Vulkan控制显卡的时候失败了，恐怕无法提供更多帮助。
建议检查显卡驱动是否可以更新，以及如果显卡有开关是否有打开。也可以截屏一下，看看有没有其他的提示信息

**Comment by flash201524** [comment]
> 软件依赖Vulkan API，这个提示是软件通过Vulkan控制显卡的时候失败了，恐怕无法提供更多帮助。 建议检查显卡驱动是否可以更新，以及如果显卡有开关是否有打开。也可以截屏一下，看看有没有其他的提示信息

找到问题了，就是Vulkan没调用出来。这种问题只会在AMD cpu+英伟达GPU的情况下出现，解决方法是更新AMD驱动
