### ISSUE TITLE
real-esrgan没有提供RealESRNet_x2plus.pth，请问你是如何训练这个pairdata的x2数据集的

### ISSUE THREAD

**Issue by luomulo** [tumuyan/SourceBook-Dataset#12]

**Comment by tumuyan** [comment]
官方仓库有release模型的   https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth

**Comment by luomulo** [comment]
> 官方仓库有release模型的 https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth

官网只有RealESRGAN_x2plus.pth，但是用pairdata训练需要RealESRNet_x2plus.pth，请问这几个option是用的哪个来训练sourcebook的。
![Snipaste_2024-06-13_10-20-55](https://github.com/tumuyan/SourceBook-Dataset/assets/96601524/97014290-c2db-4262-8e4b-3c08fc4d27b2)

**Comment by tumuyan** [comment]
我用第二个修改的，可以参考basicsr关于option的说明。没有直接能用的配置

**Comment by tumuyan** [comment]
我用第二个修改的，可以参考basicsr关于option的说明。没有直接能用的配置

**Comment by banli-ynyg** [comment]
> 官方仓库有release模型的 https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth

但是这个不是12通道的吗，你可以直接使用吗

**Comment by tumuyan** [comment]
> > 官方仓库有release模型的 https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth
> 
> 但是这个不是12通道的吗，你可以直接使用吗

可以直接用的 xintao的仓库已经设计好了怎么加载模型了
