### ISSUE TITLE
Linux 环境脚本

### ISSUE THREAD

**Issue by JYP0308** [tumuyan/SourceBook-Dataset#2]
会不会出一个Linux环境的运行脚本

**Comment by tumuyan** [comment]
其实Linux版已经做了，这周会发，目前测试看兼容性很糟

**Comment by JYP0308** [comment]
还有一个，目前是之支持png格式图片吗？有部分pdf文件运行run.bat报错  Cannot read JBIG2 image: jbig2-imageio is not installed

**Comment by tumuyan** [comment]
支持png，请提供一下报错的文件样本

**Comment by JYP0308** [comment]
https://zlibrary-asia.se/book/3553634/3ce6db

**Comment by JYP0308** [comment]
https://pan.baidu.com/s/1IBgzv7OQnv6gFv5tMsfV0w?pwd=1111
或者 
https://zlibrary-asia.se/book/3553634/3ce6db

**Comment by tumuyan** [comment]
我试着跑了下，发现原因是pdf文件中包含了JBIG2图片。 
处理pdf使用了pdfbox库，而我之前使用的pdfbox库版本较低，不支持JBIG2图片。  
升级pdfbox可以解决这个问题，但是…我的代码出了其他不太能理解的问题，需要一些时间来修复。

**Comment by tumuyan** [comment]
我对程序进行了更新，虽然还是不能处理jbig2图片，但是如果有类似问题不会发生崩溃了。
另外你提供的文件内容非常清晰的呀，没有处理的必要性。

**Comment by JYP0308** [comment]
好的，感谢，之前处理了一本阿西莫夫的人生舞台，效果非常好，这本是由于在平板上看毛刺较多，有点不舒服，想试一下。

**Comment by tumuyan** [comment]
现在已经可以把pdf中的jbig2图片导出为tiff文件了，你的这本书可以跑了。
这个图片分辨率已经高达1744*2610，没有处理的必要性。
你所看到的毛刺，我猜测是扫描之后压缩分辨率并转换为黑白图的时候，做了抖动处理——把一个带灰阶的像素转换为多个黑白的小像素，从而在体积很小的前提下看上去非常锐利清晰。
