### ISSUE TITLE
一直报错`vkCreateComputePipelines failed -1000012000`如何处理

### ISSUE THREAD

**Issue by mumuxi-git** [tumuyan/SourceBook-Dataset#3]
拖到bat之后就一直报错，`vkCreateComputePipelines failed -1000012000`，这是怎么回事呀...

具体信息如下：
input   "C:\Users\mumuxi\Desktop\TEMP\software\2023-06-11-Real-ESRGAN-Vulkan-SourceBook\pic.jpg"
output  "C:\Users\mumuxi\Desktop\TEMP\software\2023-06-11-Real-ESRGAN-Vulkan-SourceBook\pic_x2.jpg"
[0 GT 755M]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 GT 755M]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 GT 755M]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/0
[0 GT 755M]  subgroup=64  basic=0  vote=0  ballot=0  shuffle=0
load model: models/RealESRGAN-SourceBook-latest-fp16.bin
vkCreateComputePipelines failed -1000012000
new_pipeline failed
vkCreateComputePipelines failed -1000012000
new_pipeline failed
vkCreateComputePipelines failed -1000012000
new_pipeline failed
vkCreateComputePipelines failed -1000012000
new_pipeline failed
vkCreateComputePipelines failed -1000012000

**Comment by tumuyan** [comment]
能给到的建议就是更新驱动

https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

**Comment by mumuxi-git** [comment]
更新驱动后解决，感谢
